package mypackage;
// Generated 18 Apr, 2020 7:15:16 PM by Hibernate Tools 4.3.1



/**
 * Medicine generated by hbm2java
 */
public class Medicine  implements java.io.Serializable {


     private String disease;
     private String medicine;

    public Medicine() {
    }

    public Medicine(String disease, String medicine) {
       this.disease = disease;
       this.medicine = medicine;
    }
   
    public String getDisease() {
        return this.disease;
    }
    
    public void setDisease(String disease) {
        this.disease = disease;
    }
    public String getMedicine() {
        return this.medicine;
    }
    
    public void setMedicine(String medicine) {
        this.medicine = medicine;
    }




}


